-- Warning: fhis file is generated by Hephaistos, do not edit manually
-- The values here should reflect the values hex patched in the game engine
Hephaistos.ScreenWidth = 2592
Hephaistos.ScreenHeight = 1080
