ScreenData.GameStats.CategoryStartX = Hephaistos.RecomputeFixedXFromCenter(ScreenData.GameStats.CategoryStartX)
ScreenData.GameStats.CategoryStartY = Hephaistos.RecomputeFixedYFromCenter(ScreenData.GameStats.CategoryStartY)
