EpilogueData[1].Animations = {
	{ AnimationName = "Olympus_00_Backing", Delay = 0, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "Olympus_01_OuterCircle", Delay = 0, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "Olympus_01a_InnerCircle", Delay = 0, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "Olympus_02_Vignette", Delay = 0, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "Olympus_03_Background", Delay = 0, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "OlympianSigil_Hades", Delay = 49, X = ScreenCenterX, Y = ScreenCenterY, Group = "Combat_Menu_TraitTray_Overlay" },
	{ AnimationName = "OlympianSigil_Zeus", Delay = 3, X = Hephaistos.RecomputeFixedXFromCenter(960), Y = Hephaistos.RecomputeFixedYFromCenter(177), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Poseidon", Delay = 6, X = Hephaistos.RecomputeFixedXFromCenter(1230), Y = Hephaistos.RecomputeFixedYFromCenter(260), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Athena", Delay = 9, X = Hephaistos.RecomputeFixedXFromCenter(1350), Y = Hephaistos.RecomputeFixedYFromCenter(507), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Aphrodite", Delay = 12, X = Hephaistos.RecomputeFixedXFromCenter(1300), Y = Hephaistos.RecomputeFixedYFromCenter(747), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Artemis", Delay = 15, X = Hephaistos.RecomputeFixedXFromCenter(1096), Y = Hephaistos.RecomputeFixedYFromCenter(942), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Ares", Delay = 18, X = Hephaistos.RecomputeFixedXFromCenter(810), Y = Hephaistos.RecomputeFixedYFromCenter(942), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Dionysus", Delay = 21, X = Hephaistos.RecomputeFixedXFromCenter(610), Y = Hephaistos.RecomputeFixedYFromCenter(747), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Hermes", Delay = 24, X = Hephaistos.RecomputeFixedXFromCenter(546), Y = Hephaistos.RecomputeFixedYFromCenter(507), Group = "Combat_Menu_TraitTray_Overlay_Additive" }, 
	{ AnimationName = "OlympianSigil_Demeter", Delay = 27, X = Hephaistos.RecomputeFixedXFromCenter(670), Y = Hephaistos.RecomputeFixedYFromCenter(260), Group = "Combat_Menu_TraitTray_Overlay_Additive" },
}
EpilogueData[2].Animations = {
	{ AnimationName = "HandShake_08_BG", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 1.5 },
	{ AnimationName = "HandShake_07_Pillars_Right", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 1.7 },
	{ AnimationName = "HandShake_06_Pillars_Left", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 1.9 },
	{ AnimationName = "HandShake_05_Trees", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 2.1 },
	{ AnimationName = "HandShake_04_BGChars", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 2.3 },
	{ AnimationName = "HandShake_03_Vignette", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 2.5 },
	{ AnimationName = "HandShake_02_Gradient", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 2.7 },
	{ AnimationName = "HandShake_01_Characters", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 2.9 },
	{ AnimationName = "HandShake_00_FrontFx", X = ScreenCenterX, Y = ScreenCenterY, StartColor = Color.Black, EndColor = Color.White, ColorDuration = 6.1 },
}
